
spring:
  datasource:
#    url: ${db.url:}
    url: jdbc:postgresql://localhost:5432/postgres
#    username: ${db.username}
    username: postgres
    password: password
#    password: ${db.password}
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${facebook.client-id}
            client-secret: ${facebook.client-secret}
        provider:
          facebook:
            user-name-attribute: email
  flyway:
    baseline-on-migrate: true

  sql:
    init:
      mode: always

server:
  forward-headers-strategy: framework
