
spring:
  datasource:
#    url: ${db.url:}
    url: jdbc:postgresql://localhost:5432/postgres
#    username: ${db.username}
    username: postgres
    password: password
#    password: ${db.password}
  sql:
    init:
      mode: always